apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/pv/postgresql
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Recycle
