apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry
spec:
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/pv/registry
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Retain
