apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/pv/storage
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Recycle
